### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ENA256** [SuYueQiuLiang/loa-logger-cn#3]
Hi, I'm working on the KR meter. We also have some trouble breaching the system but I think we can help each out. If you are interested give me a message on discord. Friend code: ```consensus123```.

**Comment by SuYueQiuLiang** [comment]
send you, but as Amazon and Mainland China have not yet updated, we may not be able to provide much assistance at the moment. We are also temporarily suspend the existing reverse tasks bufore the patches for the KR server be synchronized
