### ISSUE TITLE
能给个联系方式吗 我看snow重新完成了新的加密方式

### ISSUE THREAD

**Issue by 1soon** [SuYueQiuLiang/loa-logger-cn#5]
美服的DPS插件我看他们重新解密成功了, 我在dis上联系了解密的那些人, 看看能不能对国服有帮助,  能给个联系方式吗?

**Comment by SuYueQiuLiang** [comment]
q 1569938823
我之前有联系过他们，但是他们不太乐意提供帮助的样子

**Comment by SuYueQiuLiang** [comment]
目前我再做的工作是从头逆向
不过即使snow他们乐意提供帮助，很多东西也只能我们自己来，opcode这类数据只能从客户端内存提取
